# allocation.py
# Author: Jitendra Suwalka
# Section: Data Science Course: SDPA_EMATM0048
# Description: Allocate monthly bouquet orders across florists, taking
#              account of each florist's speciality and time limits.

"""
Speciality-aware bouquet allocation and florist revenue contribution.

This module does NOT know anything about greenhouse stock or restocking.
It ONLY splits already-decided bouquet orders across florists, respecting:

- 80 hours per florist per month
- Half time for work in their speciality bouquet
- Equal sharing of non-speciality work
"""

from dataclasses import dataclass, field
from typing import Dict, List, Tuple

# Different Bouquet types
BOUQUET_TYPES = ["Fern-tastic", "Be-Leaf in Yourself", "You Rose to the Occasion"]

# Minutes to prepare ONE bouquet of each type
BOUQUET_TIMES_MIN = {
    "Fern-tastic": 20,
    "Be-Leaf in Yourself": 30,
    "You Rose to the Occasion": 45,
}

# Selling prices of different bouquet types
BOUQUET_PRICES = {
    "Fern-tastic": 18.50,
    "Be-Leaf in Yourself": 17.75,
    "You Rose to the Occasion": 32.50,
}

# Max No. of working hours for a florist
MAX_HOURS_PER_MONTH = 80.0  


@dataclass
class FloristState:
    """
    Lightweight wrapper around a Florist object.

    This tracks per-month production statistics so that the allocation
    code does not have to modify the original Florist instances.

    Attributes:
        florist_obj::object
            The underlying Florist instance.
        name::str
            Convenience copy of florist_obj.name for dictionary keys.
        speciality::str | None
            Name of the bouquet type this florist specialises in, or None.
        hours_used::float
            Number of working hours already allocated this month.
        revenue::float
            Total revenue generated by bouquets made by this florist.
        bouquets_made::dict[str, int]
            Counter of how many bouquets of each type this florist produced.
    """
    florist_obj: object
    name: str
    speciality: str | None
    hours_used: float = 0.0          # in hours
    revenue: float = 0.0             # £
    bouquets_made: Dict[str, int] = field(
        default_factory=lambda: {b: 0 for b in BOUQUET_TYPES}
    )

    @property
    def hours_left(self) -> float:
        """
        Compute the remaining working hours available for this florist.

        Returns:
            float
                Number of hours that can still be allocated this month,
                never negative.
        """
        return max(0.0, MAX_HOURS_PER_MONTH - self.hours_used)

    def can_do(self, minutes: float) -> bool:
        """
        Check whether at least one more bouquet of a given duration fits.

        Args:
            minutes::float
                Time in minutes required for one bouquet of the task.

        Returns:
            bool
                True if assigning one bouquet of this length would keep
                the florist within the monthly hour limit, otherwise False.
        """
        return self.hours_used + minutes / 60.0 <= MAX_HOURS_PER_MONTH

    def assign_work(self, bouquet_type: str, count: int, minutes_per_bouquet: float) -> None:
        """
        Assign actual bouquet work to this florist.

        This updates hours worked, bouquet counters and revenue at the
        same time so that all three stay in sync.

        Args:
            bouquet_type::str
                Name of the bouquet being made.
            count::int
                Number of bouquets to allocate in this step.
            minutes_per_bouquet::float
                Duration, in minutes, to produce a single bouquet of
                this type for this florist.
        """
        total_minutes = minutes_per_bouquet * count
        self.hours_used += total_minutes / 60.0
        self.bouquets_made[bouquet_type] += count
        self.revenue += count * BOUQUET_PRICES[bouquet_type]


def _round_robin_assign(
    bouquet_type: str,
    remaining: int,
    florists: List[FloristState],
    minutes_per_bouquet: float
) -> int:
    """
    Share bouquets between florists in a simple round-robin fashion.

    Each loop gives a single bouquet to the next florist that still has
    enough time for it. Florists who can no longer take on even one more
    bouquet are removed from the rotation.

    Args:
        bouquet_type::str
            The bouquet type being allocated.
        remaining::int
            Number of bouquets that still need to be assigned.
        florists::list[FloristState]
            The pool of florist states that may receive work.
        minutes_per_bouquet::float
            Duration of one bouquet of this type for the involved florists.

    Returns:
        int
            The number of bouquets that could not be assigned because all
            florists ran out of time.
    """
    if remaining <= 0 or not florists:
        return remaining

    active = florists[:]
    idx = 0

    while remaining > 0 and active:
        f = active[idx % len(active)]
        if not f.can_do(minutes_per_bouquet):
            # This florist has no time left for even one bouquet – remove from rotation
            active.pop(idx % len(active))
            continue

        # Assign exactly one bouquet at a time for fairness
        f.assign_work(bouquet_type, 1, minutes_per_bouquet)
        remaining -= 1
        idx += 1

    return remaining


def allocate_bouquets_among_florists(
    bouquet_orders: Dict[str, int],
    florists: List[object],
) -> Tuple[float, Dict[str, float], Dict[str, Dict[str, int]], Dict[str, int]]:
    """
    Allocate all requested bouquets across the available florists.

    Speciality rules are applied first: florists work at half-time for
    bouquets that match their speciality. Remaining work is then shared
    across all florists at the normal time per bouquet.

    Args:
        bouquet_orders::dict[str, int]
            Mapping from bouquet type to number of bouquets requested
            this month.
        florists::list[Florist]
            List of Florist objects with `.name` and `.speciality`
            attributes.

    Returns:
        tuple:
            total_income::float
                Total sales revenue generated by all completed bouquets.
            revenue_by_florist::dict[str, float]
                Mapping from florist name to their revenue contribution.
            bouquets_by_florist::dict[str, dict[str, int]]
                For each florist, how many bouquets of each type they made.
            unmet_demand::dict[str, int]
                For each bouquet type, how many orders could not be
                produced because all florists reached their time limits.
    """
    florist_states: List[FloristState] = [
        FloristState(
            florist_obj=f,
            name=getattr(f, "name", str(f)),
            speciality=getattr(f, "speciality", None),
        )
        for f in florists
    ]

    unmet_demand: Dict[str, int] = {b: 0 for b in BOUQUET_TYPES}

    for bouquet_type, requested_qty in bouquet_orders.items():
        if requested_qty <= 0:
            continue

        base_minutes = BOUQUET_TIMES_MIN[bouquet_type]

        # 1) Specialists for this bouquet
        specialists = [fs for fs in florist_states if fs.speciality == bouquet_type]
        remaining = requested_qty

        # 1a) Specialists work FIRST, with half time
        if specialists:
            specialised_minutes = base_minutes / 2.0
            remaining = _round_robin_assign(
                bouquet_type,
                remaining,
                specialists,
                specialised_minutes,
            )

        # 2) Any remaining bouquets of this type → shared among ALL florists at normal time
        if remaining > 0:
            remaining = _round_robin_assign(
                bouquet_type,
                remaining,
                florist_states,
                base_minutes,
            )

        # 3) If some still remain, we ran out of hours
        if remaining > 0:
            unmet_demand[bouquet_type] += remaining

    total_income = sum(fs.revenue for fs in florist_states)
    revenue_by_florist = {fs.name: round(fs.revenue, 2) for fs in florist_states}
    bouquets_by_florist = {fs.name: dict(fs.bouquets_made) for fs in florist_states}

    return total_income, revenue_by_florist, bouquets_by_florist, unmet_demand
